language: go
install:
  - go get github.com/cyfdecyf/leakybuf
  - go get code.google.com/p/go.crypto/blowfish
  - go get code.google.com/p/go.crypto/cast5
  - pushd $TRAVIS_BUILD_DIR
  - go install ./cmd/shadowsocks-local
  - go install ./cmd/shadowsocks-server
  - popd
script:
  - pushd $GOPATH/src/github.com/shadowsocks/shadowsocks-go
  - PATH=$PATH:$GOPATH/bin/ bash -x ./script/test.sh
  - popd
